#!/bin/bash

# set colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
NO_COLOR='\033[0m'
CLEAR_LINE='\r\033[K'

if /sbin/ethtool eth0 2>/dev/null | grep -q "Link detected: yes"; then
    eth0_full=$(ifconfig eth0 2>/dev/null);
    eth0=$(echo $eth0_full | grep inet | cut -d" " -f6 | head -1)
    printf "${YELLOW}eth0${NO_COLOR}\n%s\n" "$eth0"
fi

if /sbin/ethtool eth1 2>/dev/null | grep -q "Link detected: yes"; then
    eth1_full=$(ifconfig eth1 2>/dev/null)
    eth1=$(echo $eth1_full | grep inet | cut -d" " -f6 | head -1)
    printf "${YELLOW}eth0${NO_COLOR}\n%s\n" "$eth1"
fi

if /sbin/ethtool wlan0 2>/dev/null | grep -q "Link detected: yes"; then
    wlan0_full=$(ifconfig wlan0 2>/dev/null)
    wlan0=$(echo $wlan0_full | grep inet | cut -d" " -f6 | head -1)
    printf "${YELLOW}wlan0${NO_COLOR}\n%s\n" "$wlan0"
fi

if /sbin/ethtool tap0 2>/dev/null | grep -q "Link detected: yes"; then
    tap0_full=$(ifconfig tap0 2>/dev/null)
    tap0=$(echo $tap0_full | grep inet | cut -d" " -f6 | head -1)
    printf "${YELLOW}tap0${NO_COLOR}\n%s\n" "$tap0"
fi

if /sbin/ethtool tun0 2>/dev/null | grep -q "Link detected: yes"; then
    tun0_full=$(ifconfig tun0 2>/dev/null)
    tun0=$(echo $tun0_full | grep inet | cut -d" " -f6 | head -1)
    printf "${YELLOW}tun0${NO_COLOR}\n%s\n" "$tun0"
fi

exit 1
